### ISSUE TITLE
[BUG] Keystrokes in non-admin processes (except for the first one) are not blocked after startup (non-admin -> admin)

### ISSUE THREAD

**Issue by derkalaender** [VollRahm/NotEnoughHotkeys#7] opened 2020-04-07 22:38 UTC
**Describe the bug**
Very weird and specific. Starting NEH without admin and then clicking yes on the dialog box to restart as admin results in the following behaviour:
The first keystroke is blocked, but all the consecutive ones are getting through (tested in Discord, Chrome and Notepad). I was curious to see if the same would happen in an admin process, so I started Notepad++ as admin and there **every hotkey was intercepted.**

Ticking the 'Enabled' checkbox off and back on again resolves the issue. Additionally, this bug doesn't occur when starting NEH with admin privileges directly.

**Note**: Just to emphasize, the first keystroke is getting intercepted. However it doesn't have to be a configured hotkey. Pressing anything will be intercepted but anything following that, will not.
**Note also**: Just the keystroke will not be intercepted. The macro is still executed.

**To Reproduce**
1. Start NEH normally, without admin
2. Click on 'Yes' in the dialog box that offers you to restart with admin privs
3. Open up non-admin process (bug doesn't occur in admin process)
4. Press any keystroke (it will be blocked)
5. Any keystrokes following will not be intercepted <- that's the bug

**Expected behavior**
The keystroke should not slip through in this very specific edge case

**Screenshots**
-/-

**Elevation of Process:**
As already specified this bug only occurs if restarting with admin via the dialog box and not by starting the NEH directly with admin

**Additional context**
This is so weird and a real tight edge case, I'm sorry XD

**Comment by VollRahm** [comment] 2020-04-07 22:46
Seems to be an issue with the process being started twice and the process that got started first is blocking the Named Pipe, so that the new process doesn't start

**Comment by VollRahm** [comment] 2020-04-08 11:57
Apparently this bug seems to be related to #6 and is not reproducible in any case after https://github.com/VollRahm/NotEnoughHotkeys/commit/b67775a8dcfa18d675e785a903ef5d20f7d814f4, closing for now

**Closed as completed by VollRahm** 2020-04-08 11:57 UTC
Labels: bug
